feat(chart): support nodeSelector for workloads
artifacthub/hub pull request #3574
Opened 2024-01-04 19:25 UTC by jking916

Currently there is no way in the Helm chart to configure Artifact Hub to run on specific nodes in a Kubernetes cluster. This PR adds support for node selectors for each workload (the postgres chart already supports this).

2024-01-08 13:39 UTC, tegioz requested changes
Thanks @jking916!

Could you please bump the chart version to `1.16.1-4` and rebase from master?

2024-01-08 16:17 UTC, jking916 commented
Done. Thanks for reviewing @tegioz!

2024-01-08 17:47 UTC, tegioz approved these changes
Thanks!

2024-01-08 17:59 UTC, merged

2024-01-09 21:34 UTC, jking916 commented
When can we expect a new chart version to be released? Is that done separately from Artifact Hub itself?

2024-01-10 06:46 UTC, tegioz commented
I think we'll probably cut a new release next week.